version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoicesdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/invoicesdb?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    ports:
      - "3000:3000"

volumes:
  db-data:
